#!/bin/bash

#SBATCH --partition=gpu_shared_course
#SBATCH --gres=gpu:1
#SBATCH --job-name=ExampleJob
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=3
#SBATCH --time=04:00:00
#SBATCH --mem=32000M
#SBATCH --output=slurm_output_%A.out

module purge
module load 2020
module load Miniconda3/4.7.12.1

# Your job starts in the directory where you call sbatch
cd ./
# Activate your environment
source activate dl2020
# Run your code
srun python3 -u train_convnet_pytorch.py
echo "Done"